"""
provenance.py -- keep synthetic test audio out of the real dataset.

make_test_data.py exists so the tools can be proved to work before range day.
Its output is fake, and fake audio sitting in a folder looks exactly like real
audio: same extension, same sample rate, same waveform shape. Nothing about a
WAV file announces that it was generated.

So every directory make_test_data.py writes gets a marker file, and every tool
that reads audio checks for it. A synthetic file cannot silently become a
measurement.
"""

import os

MARKER = '_SYNTHETIC_DO_NOT_USE.txt'

MARKER_TEXT = """\
SYNTHETIC TEST DATA -- NOT REAL MEASUREMENTS

Every .wav in this directory was generated by make_test_data.py to exercise the
toolkit. None of it was recorded. It must never enter the dataset, appear in a
report, or be compared against anything.

The tools in this toolkit look for this file and will refuse or loudly warn.
Deleting it to silence a warning defeats the only safeguard there is.
"""


def mark(directory):
    """Stamp a directory as synthetic."""
    with open(os.path.join(directory, MARKER), 'w') as f:
        f.write(MARKER_TEXT)


def is_synthetic(path):
    """True if this file or directory is inside a marked synthetic set."""
    d = path if os.path.isdir(path) else os.path.dirname(os.path.abspath(path))
    # Walk up a couple of levels: ingest.py writes events/ inside testdata/
    for _ in range(3):
        if os.path.exists(os.path.join(d, MARKER)):
            return True
        parent = os.path.dirname(d)
        if parent == d:
            break
        d = parent
    return False


def guard(path, tool, allow_flag='--allow-synthetic', allowed=False):
    """Refuse synthetic input unless explicitly allowed.

    Returns True if the input is synthetic (and allowed), False if real.
    Exits if synthetic and not allowed.
    """
    import sys
    if not is_synthetic(path):
        return False
    if allowed:
        print(f"\n  *** {tool}: SYNTHETIC TEST DATA -- results are not "
              f"measurements ***\n", file=sys.stderr)
        return True
    print(f"\n  REFUSING: {path}\n"
          f"  is synthetic test data from make_test_data.py, not a recording.\n"
          f"  It must not enter the dataset.\n\n"
          f"  If you are deliberately exercising the toolkit, pass "
          f"{allow_flag}.\n", file=sys.stderr)
    sys.exit(3)
